name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  dart_frog: ^1.0.1
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.7.1
  dbcrypt: ^2.0.0
  mysql_client: ^0.0.27

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.19.2
  very_good_analysis: ^5.1.0
